### ISSUE TITLE
no file named 'sciCAR_cell_annot.txt' is provided

### ISSUE THREAD

**Issue by JiahaoChow** [bm2-lab/scMVP#2]
Hi~ I am running your demo code and an error raised about the missing file named 'sciCAR_cell_annot.txt'. 
It would be very kind of you to tell me how to tackle the problem. Thanks.

**Comment by adamtongji** [comment]
Sorry for missing the cell annotation files. We have uploaded the annotation files to the cloud disk.

**Comment by JiahaoChow** [comment]
Thank you very much!
